

class EffectNames():
    TEXT_EFFECT = "TEXT"
    COLOR_EFFECT = "COLOR"


class SerializedKeys:

    ### FRAME HANDLER
    FRAME_LIST = "FRAME_LIST"

    ### SCENE FRAME
    FADE_TIME = "FADE_TIME"
    SCENE_TIME = "SCENE_TIME"
    EFFECT_LIST = "EFFECTS"

    ### EFFECTS
    EFFECT_NAME = "FX_NAME"

    # COLOR EFFECT
    COLOR_VALUE_HEX = "COLOR_HEX"

    # TEXT EFFECT
    TEXT_VALUE_KEY = "TEXT"

