
# SETUP PATH TO APPLICATION FILES
APPLICATION_BASE_PATH = "B:/workspace/LightStick/"
INDEX_HTML_PATH = "MsvClient/Html/index.html"

# MSV CONFIG
MSG_NUM_MSV_HOST = "t0.mcorp.no:8091"
MSG_NUM_MSV_ID = 22

PLAYBACK_MSV_HOST = "t0.mcorp.no:8091"
PLAYBACK_MSV_ID = 18

# SETUP LOGGING
LOG_FILE_PATH = "log/"
LOG_FILE_NAME = "userLog"
LOG_FILE_ENDING = ".log"
LOG_INTERVAL_IN_SEC = 60

# RANDOM SHOW CONFIGURATION
ENTER_RANDOM_MODE_AFTER_SEC = 300
RANDOM_SHOW_FOLDER = "B:\LightStickShows"
RANDOM_INTERVAL_SEC_MIN = 30
RANDOM_INTERVAL_SEC_MAX = 240
RANDOM_BPM_DELAY_NEXT_SHOW = 4
