
APPLICATION_BASE_PATH = "B:/workspace/LightStick/"
INDEX_HTML = "MsvClient/Html/index.html"

LOG_FILE = "/log.txt"
LOG_INTERVAL = 10
LOG_BACKUPS = 2

RANDOM_SHOW_FOLDER = "B:\LightStickShows"
RANDOM_INTERVAL_SEC_MIN = 10
RANDOM_INTERVAL_SEC_MAX = 60
RANDOM_START_DELAY = 4